on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: prakashsurya/actions/linux-pkg-build@master
        with:
          package: zfs
